# Generated by Django 4.1.7 on 2023-02-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
